version: "{build}"
max_jobs: 10
skip_branch_with_pr: false
skip_commits:
  message: /.*\[nobuild\].*/
skip_tags: false

environment:
    GIT_DAEMON_PATH:   "C:\\Program Files\\Git\\mingw64\\libexec\\git-core"
    CYGWIN_GIT_PATH:   "C:\\cygwin\\bin;%GIT_DAEMON_PATH%"
    CYGWIN64_GIT_PATH: "C:\\cygwin64\\bin;%GIT_DAEMON_PATH%"
    APPVEYOR_ARTIFACT_UPLOAD_TIMEOUT: 60
    PYTHON: "C:\\Python36-x64"
    PYTHON_VERSION: "3.6"
    GIT_PATH: "%GIT_DAEMON_PATH%"
    GH_TOKEN:
      secure: H9M/aPctMSk1+0AWe/l5D0U3oXto404/4UYiPMCECpjy0llgb8cBKTRyr20UDWdX
    GH_MAIL:
      secure: hyFFOoK6WbxtLxy2jOGlOPbRJ33Al8E1B0QeT+qUqJ8=


matrix:
    fast_finish: true

init:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  # Check that we have the expected version and architecture for Python
  - set PATH=%PYTHON%;%PYTHON%\Scripts;C:\MinGW\msys\1.0\bin;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""

install:
  - cmd: pip install edlm

build_script:
  - cmd: edlm --debug convert pdf .


artifacts:
  - path: '*.pdf'
    name: document
    type: File

deploy:
  provider: FTP
  protocol: sftp
  host:
    secure: 5ySqGu0Sy46I/vsKje7UrC3zMHw8+ouvqbc3wbSkpUg=
  username: 'docs'
  password:
    secure: 3UqjnpgLIcOlO+lXGID86Q==
  folder: 'docs'
  on:
    branch: master